# Generated by Django 2.1.5 on 2019-04-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMSGroupYaoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmsid', models.IntegerField(default=0)),
                ('bmsgid', models.IntegerField(default=0)),
                ('tsp', models.DateTimeField(default='2018-01-01 00:00:00.000')),
                ('bat_gid_of_min_temp', models.IntegerField(default=0)),
                ('bat_gid_of_max_temp', models.IntegerField(default=0)),
                ('bat_gid_of_min_voltage', models.IntegerField(default=0)),
                ('bat_gid_of_max_voltage', models.IntegerField(default=0)),
                ('bat_min_temp', models.IntegerField(default=0)),
                ('bat_max_temp', models.IntegerField(default=0)),
                ('bat_min_voltage', models.IntegerField(default=0)),
                ('bat_max_voltage', models.IntegerField(default=0)),
                ('SOC', models.IntegerField(default=0)),
                ('SOH', models.IntegerField(default=0)),
                ('chargable_kwh', models.IntegerField(default=0)),
                ('dischargable_kwh', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('voltage', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('total_charged_kwh', models.IntegerField(default=0)),
                ('total_discharged_kwh', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'BMSGroupYaoce',
            },
        ),
        migrations.CreateModel(
            name='BMSYaoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmsid', models.IntegerField(default=0)),
                ('tsp', models.DateTimeField(default='2018-01-01 00:00:00.000')),
                ('bat_gid_of_min_temp', models.IntegerField(default=0)),
                ('bat_gid_of_max_temp', models.IntegerField(default=0)),
                ('bat_gid_of_min_voltage', models.IntegerField(default=0)),
                ('bat_gid_of_max_voltage', models.IntegerField(default=0)),
                ('bat_min_temp', models.IntegerField(default=0)),
                ('bat_max_temp', models.IntegerField(default=0)),
                ('bat_min_voltage', models.IntegerField(default=0)),
                ('bat_max_voltage', models.IntegerField(default=0)),
                ('SOC', models.IntegerField(default=0)),
                ('SOH', models.IntegerField(default=0)),
                ('chargable_kwh', models.IntegerField(default=0)),
                ('dischargable_kwh', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('voltage', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('total_charged_kwh', models.IntegerField(default=0)),
                ('total_discharged_kwh', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'BMSYaoce',
            },
        ),
        migrations.CreateModel(
            name='CurrentError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueid', models.CharField(help_text='故障唯一ID号，和历史故障ID号公用', max_length=30)),
                ('ecode', models.TextField(help_text='故障代码')),
                ('abstrct', models.TextField(help_text='故障摘要信息')),
                ('econtext', models.TextField(help_text='故障详细内容，存储格式为json')),
                ('eclass', models.CharField(help_text='故障类型', max_length=100)),
                ('elevel', models.IntegerField(help_text='故障级别')),
                ('etsp', models.DateTimeField(default='2018-01-01 00:00:00', help_text='故障产生时间')),
            ],
            options={
                'db_table': 'CurrentError',
            },
        ),
        migrations.CreateModel(
            name='GridPageBinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='/grid/', max_length=512)),
            ],
            options={
                'db_table': 'GridPageBinder',
            },
        ),
        migrations.CreateModel(
            name='HistoryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueid', models.CharField(help_text='故障唯一ID号，从当前故障号继承', max_length=30)),
                ('ecode', models.TextField(help_text='故障代码')),
                ('abstrct', models.TextField(help_text='故障摘要信息')),
                ('econtext', models.TextField(help_text='故障详细内容，存储格式为json')),
                ('eclass', models.CharField(help_text='故障类型', max_length=100)),
                ('elevel', models.IntegerField(help_text='故障级别')),
                ('etsp_begin', models.DateTimeField(default='2018-01-01 00:00:00', help_text='故障产生时间')),
                ('etsp_end', models.DateTimeField(default='2018-01-01 00:00:00', help_text='故障处理时间')),
                ('econfirm_tsp', models.DateTimeField(default='2018-01-01 00:00:00', help_text='故障确认时间')),
                ('econfirm_user', models.CharField(default='nobody', help_text='故障确认人员', max_length=100)),
                ('econfirm_sign', models.TextField(help_text='故障确认签名及原因备注说明')),
            ],
            options={
                'db_table': 'HistoryError',
            },
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='system', help_text='类型名称', max_length=60)),
                ('code', models.IntegerField(blank=True, default=0, help_text='事件代码', null=True)),
                ('datetime', models.DateTimeField(default='2018-01-01 00:00:00.000', help_text='事件产生时戳')),
                ('master', models.IntegerField(blank=True, default=0, help_text='设备主索引号', null=True)),
                ('slave', models.IntegerField(blank=True, default=0, help_text='设备次索引号', null=True)),
                ('body', models.TextField(default='无', help_text='事件内容')),
                ('user', models.CharField(default='root', help_text='事件记录人', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PCSYaoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcsid', models.IntegerField(default=0)),
                ('tsp', models.DateTimeField(default='2018-01-01 00:00:00.000')),
                ('dc_power', models.IntegerField(default=0)),
                ('dc_voltage', models.IntegerField(default=0)),
                ('dc_current', models.IntegerField(default=0)),
                ('grid_freq', models.IntegerField(default=0)),
                ('Vab', models.IntegerField(default=0)),
                ('Vbc', models.IntegerField(default=0)),
                ('Vca', models.IntegerField(default=0)),
                ('Ia', models.IntegerField(default=0)),
                ('Ib', models.IntegerField(default=0)),
                ('Ic', models.IntegerField(default=0)),
                ('year_discharge_kwh_total', models.IntegerField(default=0)),
                ('year_discharge_time_total', models.IntegerField(default=0)),
                ('charge_kwh_total', models.IntegerField(default=0)),
                ('discharge_kwh_total', models.IntegerField(default=0)),
                ('day_charge_kwh_total', models.IntegerField(default=0)),
                ('day_discharge_kwh_total', models.IntegerField(default=0)),
                ('day_charge_time_total', models.IntegerField(default=0)),
                ('day_discharge_time_total', models.IntegerField(default=0)),
                ('month_charge_kwh_total', models.IntegerField(default=0)),
                ('month_discharge_kwh_total', models.IntegerField(default=0)),
                ('month_charge_time_total', models.IntegerField(default=0)),
                ('month_discharge_time_total', models.IntegerField(default=0)),
                ('charge_count', models.IntegerField(default=0)),
                ('discharge_count', models.IntegerField(default=0)),
                ('year_charge_time_total', models.IntegerField(default=0)),
                ('year_charge_kwh_total', models.IntegerField(default=0)),
                ('charge_time_total', models.IntegerField(default=0)),
                ('discharge_time_total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PCSYaoce',
            },
        ),
        migrations.CreateModel(
            name='SystemRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(default='untitled', help_text='键名', max_length=100)),
                ('value', models.TextField(default='value', help_text='键值', max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=1024)),
                ('enabled', models.BooleanField(default=True)),
                ('born', models.DateTimeField(default='2019-01-01 00:00:00')),
                ('target', models.CharField(default='None', max_length=100)),
                ('json_data', models.TextField(default='')),
            ],
            options={
                'db_table': 'UserDefinedGrid',
            },
        ),
        migrations.AddField(
            model_name='gridpagebinder',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.UserDefinedGrid'),
        ),
    ]
