# Generated by Django 2.0.5 on 2018-05-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名称', help_text='这个摘要的名称', max_length=40)),
                ('text', models.CharField(default='显示字符串', help_text='这个摘要的显示字符串', max_length=40)),
                ('datasource', models.TextField(default='api:///v1.0/realtime/', help_text='这个摘要点的数据来源')),
                ('format', models.CharField(blank=True, default='k=1;b=0;dot=0;mask=0x00000001;', help_text='这个值显示出来的配置字符串', max_length=200)),
                ('unit', models.CharField(blank=True, default='', help_text='这个值的显示单位符号', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='这个值的显示顺序')),
                ('display', models.BooleanField(default=True, help_text='这个值是否能够显示')),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='数据采集器', help_text='数据采集器名称', max_length=100)),
                ('period', models.IntegerField(default=600, help_text='数据采集周期，单位是秒')),
                ('protocol', models.CharField(default='http://', help_text='数据采集协议的名称', max_length=100)),
                ('host', models.CharField(default='127.0.0.1:8083', help_text='数据源地址', max_length=500)),
                ('apipaths', models.TextField(default='/v1.0/realtime/;', help_text='RestFulAPI的路径， 用分号分隔多个')),
                ('disabled', models.BooleanField(default=False, help_text='这个数据源是否被禁用')),
                ('type', models.CharField(default='single-yaoce', help_text='采集器类型', max_length=40)),
                ('operator', models.CharField(default='operate-origin', help_text='数据处理方式', max_length=40)),
                ('record', models.BooleanField(default=True, help_text='是否记录历史数据, 决定了update/insert')),
                ('maxcount', models.IntegerField(default=100, help_text='记录条数的最大值，<=0表示不设置上限')),
            ],
        ),
        migrations.CreateModel(
            name='CollectorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(help_text='记录的时间点')),
                ('data', models.TextField(help_text='记录的内容，用json记录')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Collector')),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名称', help_text='这个摘要的名称', max_length=40)),
                ('count', models.IntegerField(default=48, help_text='这个折线图表上显示的点个数')),
                ('width', models.IntegerField(default=12, help_text='这个图表所占column的宽度，总和不能超过12')),
                ('order', models.IntegerField(default=0, help_text='这个值的显示顺序')),
                ('display', models.BooleanField(default=True, help_text='这个值是否能够显示')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Collector')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='[页面标题]', help_text='页面标题内容', max_length=100)),
                ('name', models.CharField(default='[页面名称]', help_text='页面名称内容', max_length=20)),
                ('devicesn', models.IntegerField(default=0, help_text='设备索引编号')),
                ('template', models.TextField(default='default.html', help_text='页面的模板文件')),
                ('jsfiles', models.TextField(blank=True, default='', help_text='这个页面的js文件列表')),
                ('cssfiles', models.TextField(blank=True, default='', help_text='这个页面的css文件列表')),
                ('display', models.BooleanField(default=True, help_text='控制这个页面是否能显示出来')),
                ('display_order', models.IntegerField(default=0, help_text='这个页面在显示栏中的索引位置')),
                ('json', models.TextField(blank=True, help_text='这个页面需要带给js的json数据内容')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='YaoCe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名称', help_text='这个摘要的名称', max_length=40)),
                ('text', models.CharField(default='显示字符串', help_text='这个摘要的显示字符串', max_length=40)),
                ('datasource', models.TextField(default='api:///v1.0/realtime/', help_text='这个摘要点的数据来源')),
                ('format', models.CharField(blank=True, default='k=1;b=0;dot=0;mask=0x00000001;', help_text='这个值显示出来的配置字符串', max_length=200)),
                ('unit', models.CharField(blank=True, default='', help_text='这个值的显示单位符号', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='这个值的显示顺序')),
                ('display', models.BooleanField(default=True, help_text='这个值是否能够显示')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Page')),
            ],
        ),
        migrations.CreateModel(
            name='YaoXin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名称', help_text='这个摘要的名称', max_length=40)),
                ('text', models.CharField(default='显示字符串', help_text='这个摘要的显示字符串', max_length=40)),
                ('datasource', models.TextField(default='api:///v1.0/realtime/', help_text='这个摘要点的数据来源')),
                ('format', models.CharField(blank=True, default='k=1;b=0;dot=0;mask=0x00000001;', help_text='这个值显示出来的配置字符串', max_length=200)),
                ('unit', models.CharField(blank=True, default='', help_text='这个值的显示单位符号', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='这个值的显示顺序')),
                ('display', models.BooleanField(default=True, help_text='这个值是否能够显示')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Page')),
            ],
        ),
        migrations.AddField(
            model_name='grid',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Page'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Page'),
        ),
    ]
