# Generated by Django 2.0.5 on 2018-05-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_grid_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='名称', help_text='这个数据点的短名称', max_length=100)),
                ('access_path', models.TextField(help_text='访问路径')),
                ('k', models.FloatField(default=1.0, help_text='数据点斜率')),
                ('b', models.FloatField(default=0, help_text='数据点偏移')),
                ('mask', models.IntegerField(default=2147483647, help_text='数据点值掩码')),
                ('dot', models.IntegerField(default=0, help_text='小数点位数')),
                ('unit', models.CharField(blank=True, default='', help_text='这个值的显示单位符号', max_length=20)),
                ('max_record', models.IntegerField(default=1, help_text='这个数据点的最大记录条数')),
            ],
        ),
        migrations.CreateModel(
            name='DataPointRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default='2018-01-01 00:00:00', help_text='记录存储时间')),
                ('record', models.TextField(help_text='记录的数据，用json存储')),
                ('datapoint', models.ForeignKey(help_text='记录的数据点ID', on_delete=django.db.models.deletion.CASCADE, to='ui.DataPoint')),
            ],
        ),
        migrations.CreateModel(
            name='DataPointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='类型', help_text='数据点类型', max_length=100)),
                ('name', models.CharField(default='名称', help_text='类型名称', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名称', help_text='这个元素的名称', max_length=40)),
                ('order', models.IntegerField(default=0, help_text='这个值的显示顺序')),
                ('count', models.IntegerField(default=1, help_text='显示的数据点个数，用于图表显示')),
                ('display', models.BooleanField(default=True, help_text='这个值是否能够显示')),
                ('datapoint', models.ForeignKey(help_text='数据点', on_delete=django.db.models.deletion.CASCADE, to='ui.DataPoint')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Page')),
            ],
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='类型', help_text='显示元素类型', max_length=100)),
                ('name', models.CharField(default='名称', help_text='显示元素类型名称', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='abstract',
            name='page',
        ),
        migrations.RemoveField(
            model_name='collectorrecord',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='grid',
            name='datasource',
        ),
        migrations.RemoveField(
            model_name='grid',
            name='page',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.RemoveField(
            model_name='yaoce',
            name='page',
        ),
        migrations.RemoveField(
            model_name='yaoxin',
            name='page',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='apipaths',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='maxcount',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='record',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='type',
        ),
        migrations.DeleteModel(
            name='Abstract',
        ),
        migrations.DeleteModel(
            name='CollectorRecord',
        ),
        migrations.DeleteModel(
            name='Grid',
        ),
        migrations.DeleteModel(
            name='YaoCe',
        ),
        migrations.DeleteModel(
            name='YaoXin',
        ),
        migrations.AddField(
            model_name='element',
            name='type',
            field=models.ForeignKey(help_text='这个元素的类型', on_delete=django.db.models.deletion.CASCADE, to='ui.ElementType'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='datatype',
            field=models.ForeignKey(help_text='这个数据点的类型', on_delete=django.db.models.deletion.CASCADE, to='ui.DataPointType'),
        ),
        migrations.AddField(
            model_name='collector',
            name='datapoints',
            field=models.ManyToManyField(help_text='这个采集器下属的数据点列表', to='ui.DataPoint'),
        ),
    ]
