# Generated by Django 2.0.5 on 2018-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20180523_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='datapoint',
        ),
        migrations.AddField(
            model_name='element',
            name='datapoint',
            field=models.ManyToManyField(help_text='数据点列表', to='ui.DataPoint'),
        ),
    ]
