# Generated by Django 2.0.5 on 2018-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20180523_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementtype',
            name='width',
            field=models.IntegerField(default=12, help_text='这个元素类型的参数值， 主要用于图表宽度确定'),
        ),
    ]
