# Generated by Django 2.0.5 on 2018-05-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_elementtype_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='refer_count',
            field=models.IntegerField(default=0, help_text='这个数据点在系统中被引用的次数'),
        ),
    ]
