# Generated by Django 2.0.5 on 2018-05-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_datapoint_refer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapointrecords',
            name='record',
            field=models.TextField(blank=True, help_text='记录的数据，用json存储'),
        ),
    ]
