# Generated by Django 2.0.5 on 2018-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20180524_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='full_name',
            field=models.CharField(default='完整名称', help_text='这个数据点的完整名称', max_length=200),
        ),
    ]
