# Generated by Django 2.0.5 on 2018-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_datapoint_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='system', help_text='类型名称', max_length=60)),
                ('code', models.IntegerField(blank=True, default=0, help_text='事件代码', null=True)),
                ('datetiem', models.DateTimeField(default='2018-01-01 00:00:00.000', help_text='事件产生时戳')),
                ('master', models.IntegerField(blank=True, default=0, help_text='设备主索引号', null=True)),
                ('slave', models.IntegerField(blank=True, default=0, help_text='设备次索引号', null=True)),
                ('body', models.TextField(default='无', help_text='事件内容')),
            ],
        ),
    ]
