# Generated by Django 2.0.5 on 2018-05-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_historyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyrecord',
            old_name='datetiem',
            new_name='datetime',
        ),
    ]
