# Generated by Django 2.0.5 on 2018-07-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20180605_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(default='untitled', help_text='键名', max_length=100)),
                ('value', models.TextField(default='value', help_text='键值', max_length=4096)),
            ],
        ),
    ]
