# Generated by Django 2.0.5 on 2018-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_systemrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSYaoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmsid', models.IntegerField(default=0)),
                ('tsp', models.DateTimeField(default='2018-01-01 00:00:00.000')),
                ('bat_gid_of_min_temp', models.IntegerField(default=0)),
                ('bat_gid_of_max_temp', models.IntegerField(default=0)),
                ('bat_gid_of_min_voltage', models.IntegerField(default=0)),
                ('bat_gid_of_max_voltage', models.IntegerField(default=0)),
                ('bat_min_temp', models.IntegerField(default=0)),
                ('bat_max_temp', models.IntegerField(default=0)),
                ('bat_min_voltage', models.IntegerField(default=0)),
                ('bat_max_voltage', models.IntegerField(default=0)),
                ('SOC', models.IntegerField(default=0)),
                ('SOH', models.IntegerField(default=0)),
                ('chargable_kwh', models.IntegerField(default=0)),
                ('dischargable_kwh', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('voltage', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('total_charged_kwh', models.IntegerField(default=0)),
                ('total_discharged_kwh', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'BMSYaoce',
            },
        ),
        migrations.CreateModel(
            name='CurrentError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueid', models.CharField(help_text='故障唯一ID号，和历史故障ID号公用', max_length=30)),
                ('ecode', models.TextField(help_text='故障代码')),
                ('abstrct', models.TextField(help_text='故障摘要信息')),
                ('econtext', models.TextField(help_text='故障详细内容，存储格式为json')),
                ('eclass', models.CharField(help_text='故障类型', max_length=100)),
                ('elevel', models.IntegerField(help_text='故障级别')),
                ('etsp', models.DateTimeField(default='2018-01-01 00:00:00', help_text='故障产生时间')),
            ],
            options={
                'db_table': 'CurrentError',
            },
        ),
        migrations.CreateModel(
            name='HistoryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueid', models.CharField(help_text='故障唯一ID号，从当前故障号继承', max_length=30)),
                ('ecode', models.TextField(help_text='故障代码')),
                ('abstrct', models.TextField(help_text='故障摘要信息')),
                ('econtext', models.TextField(help_text='故障详细内容，存储格式为json')),
                ('eclass', models.CharField(help_text='故障类型', max_length=100)),
                ('elevel', models.IntegerField(help_text='故障级别')),
                ('etsp_begin', models.DateTimeField(default='2018-01-01 00:00:00', help_text='故障产生时间')),
                ('etsp_end', models.DateTimeField(default='2018-01-01 00:00:00', help_text='故障处理时间')),
                ('econfirm_tsp', models.DateTimeField(default='2018-01-01 00:00:00', help_text='故障确认时间')),
                ('econfirm_user', models.CharField(default='nobody', help_text='故障确认人员', max_length=100)),
                ('econfirm_sign', models.TextField(help_text='故障确认签名及原因备注说明')),
            ],
            options={
                'db_table': 'HistoryError',
            },
        ),
    ]
