# Generated by Django 2.1.3 on 2018-12-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_bmsyaoce_currenterror_historyerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSGroupYaoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmsid', models.IntegerField(default=0)),
                ('bmsgid', models.IntegerField(default=0)),
                ('tsp', models.DateTimeField(default='2018-01-01 00:00:00.000')),
                ('bat_gid_of_min_temp', models.IntegerField(default=0)),
                ('bat_gid_of_max_temp', models.IntegerField(default=0)),
                ('bat_gid_of_min_voltage', models.IntegerField(default=0)),
                ('bat_gid_of_max_voltage', models.IntegerField(default=0)),
                ('bat_min_temp', models.IntegerField(default=0)),
                ('bat_max_temp', models.IntegerField(default=0)),
                ('bat_min_voltage', models.IntegerField(default=0)),
                ('bat_max_voltage', models.IntegerField(default=0)),
                ('SOC', models.IntegerField(default=0)),
                ('SOH', models.IntegerField(default=0)),
                ('chargable_kwh', models.IntegerField(default=0)),
                ('dischargable_kwh', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('voltage', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('total_charged_kwh', models.IntegerField(default=0)),
                ('total_discharged_kwh', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'BMSGroupYaoce',
            },
        ),
    ]
